baseurl = "/"
languageCode = "en-us"
title = "PoojaSethiya"
theme = "dream"
googleAnalytics = ""
disqusShortname = "poojasethiya"
ignoreFiles = ["\\.Rmarkdown$", "_files$", "_cache$"]
enableRobotsTXT = true
relativeURLs = true
paginate = 7
canonifyurls = true
toc = false

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    twitterAuthor = "@xvrdm"
    twitterSite = "@Sethiyapooja"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    
    # background = "black"
  backgroundImage = "/me/background.JPG"
  linkColor = "seagreen"

  author = "PoojaSethiya"
  description = "Pooja's blog"
  avatar = "/me/avatar.jpg"
  motto = ""

  email = "poojasethiya24@gmail.com"
  github = "sethiyap"
  linkedin = "pooja-sethiya-9b969b23"
  instagram = "https://www.instagram.com/sethiya_pooja/"
  
  # twitter = "//twitter.com/Sethiyapooja"
    
  siteStartYear = 2020

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
  
  
