---
title: "About Me"
date: 2020-03-29T17:54:43+05:30
draft: TRUE
css: "static/css/font.css"
---

Hello, my name is Pooja Sethiya. I'm genomics data analyst with profound experience in analysis of fungal genomics data. I use R, Rmarkdown and statistical tools to analyze and visualize data. Currently, I am Ph.D. candidate at University of Macau, Macau where I have worked on [RNASeq](https://github.com/sethiyap/Cg_oxidative_stress/blob/master/CgOxidativeStressPaper.md), [ChIPSeq](https://sethiyap.github.io/FungalSporeAnalysis/), and [integrated analysis](https://github.com/sethiyap/FungalTranscriptStability) of genomics data. I always seek for novel approaches to gain biological insights. 

I have keen interest in learning advanced R and developing [tools and packages](https://sethiyap.github.io/fastaR/) in R for their handy and customizable use. I strongly believe in reproducible research and hence for majority of my work I have prepared [reports and summary](https://sethiyap.github.io/FungalSporeAnalysis/articles/pkgdown.html) using R-markdown.

Browse my list of [projects](https://github.com/sethiyap) or review my full curriculum vitae [(resume)](img/SethiyaCurriculum_Vitae_2021_forWebsite.pdf). 

## Other than data analysis...

I also like to spend time in creative activities like [painting](https://www.instagram.com/sethiyapp/), [photography](https://www.instagram.com/sethiya_pooja/) and [video editing](https://www.youtube.com/channel/UCv59hK-i9_j9qn5l9VEPCQA).


## Reach out..
Connect with me if you think we can something awesome together, drop a mail at poojasethiya24@gmail.com 
